service: pokemon-test

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: dev

functions:
  getPokemon:
    handler: dist/handler.getPokemon
    events:
      - httpApi:
          path: /pokemon/{name}
          method: get

  listPokemons:
    handler: dist/handler.listPokemons
    timeout: 29
    memorySize: 1024
    events:
      - httpApi:
          path: /pokemon
          method: get

package:
  patterns:
    - 'dist/**'
    - '!node_modules/**'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 3002
